# Generated by Django 2.2.16 on 2020-09-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='期限日')),
            ],
            options={
                'verbose_name': 'TODO',
                'verbose_name_plural': 'TODO',
                'db_table': 'todo',
            },
        ),
    ]
